site_name: FM Lab
site_url: https://docs.fmlab.no/

site_author: Fredrick Myrvoll
site_description: Tutorials, tips and tricks for homelabs and cloud infrastructure whenever i feel a writers itch

repo_name: frealmyr/docs.fmlab.no
repo_url: https://github.com/frealmyr/docs.fmlab.no

strict: false # Fail build if there are broken links, incompatible with docker serve on 0.0.0.0
docs_dir: docs/

nav:
  - index.md
  - Homelab:
      - homelab/index.md
      - Network:
        - homelab/network/index.md
        - DNS: homelab/network/dns.md
        - Routing: homelab/network/routing.md
        - Reverse Proxy: homelab/network/reverse-proxy.md
      - Docker:
        - traefik: homelab/docker/traefik.md
        - rootless docker: homelab/docker/rootless-docker.md
  - Workstation:
    - workstation/index.md
    - Configuration:
      - dotfiles: workstation/configuration/dotfiles.md
      - smb auto-mount: workstation/configuration/smb-automount.md
    - Laptop:
      - workstation/laptop/lenovo-x1-gen9.md

theme:
  name: material
  icon:
    logo: material/dns
  #favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.suggest

plugins:
  - img2fig
  - bootstrap-tables
  - git-revision-date-localized
  - mermaid2:
      arguments:
        theme: dark
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - assets/css/tables.css
  - assets/css/images.css
  - assets/css/codehilite.css
  - assets/css/footer.css
  - assets/css/custom.css