site_name: "FM Lab"
site_url: 'https://fmlab.no/'

site_author: 'Fredrick Myrvoll'
site_description: 'Guides & tips for the homelab community'

repo_name: 'frealmyr/fmlab.no'
repo_url: 'https://github.com/frealmyr/fmlab.no'

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Home: index.md
  - Homelab:
      - Introduction: homelab/introduction.md
      - Host setup: homelab/host-setup.md
      - Traefik:
          - Setup Traefik: homelab/traefik.md
          - Using Traefik: homelab/traefik-usage.md
      - PiHole: homelab/pihole.md
  - Advanced Topics:
      - Rootless docker: homelab/rootless-docker.md
  - Current hardware: current-hardware.md

theme:
  name: 'material'
  logo:
    icon: 'dns'
  palette:
    primary: 'cyan'
    accent: 'purple'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'

plugins:
  - img2fig
  - bootstrap-tables
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite:
      linenums: true

extra:
  disqus: 'fmlab'

extra_css:
  - assets/css/tables.css
  - assets/css/images.css
  - assets/css/dark_theme.css
  - assets/css/codehilite.css
