site_name: "FM Lab"
site_url: 'https://fmlab.no/'

site_author: 'Fredrick Myrvoll'
site_description: 'Guides & tips for the homelab community'

repo_name: 'frealmyr/fmlab.no'
repo_url: 'https://github.com/frealmyr/fmlab.no'

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Home: index.md
  - Homelab:
      - Introduction: homelab/introduction.md
      - Host setup: homelab/host-setup.md
      - Traefik:
          - Setup Traefik: homelab/traefik.md
          - Using Traefik: homelab/traefik-usage.md
      - PiHole: homelab/pihole.md
  - Advanced Topics:
      - Rootless docker: homelab/rootless-docker.md
  - Current hardware: current-hardware.md

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    primary: cyan
    accent: purple
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest

plugins:
  - img2fig
  - bootstrap-tables
  - git-revision-date-localized
  - mermaid2:
      arguments:
        theme: 'dark'
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

#extra_css:
  #- assets/css/tables.css
  #- assets/css/images.css
  #- assets/css/dark_theme.css
  #- assets/css/codehilite.css
