site_name: "Frealmyr's Homelab"
site_url: 'https://fmlab.no/'

site_author: 'Fredrick Myrvoll'
site_description: 'Guides & tips for the homelab community'

repo_name: 'frealmyr/fmlab.no'
repo_url: 'https://github.com/frealmyr/fmlab.no'

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Home: index.md
  - Homelab:
      - Introduction: homelab/introduction.md
      - Traefik: homelab/traefik.md
  - Testing: testing.md

theme:
  name: 'material'
  logo:
    icon: 'developer_board'
  palette:
    primary: 'deep purple'
    accent: 'purple'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'

plugins:
  - search
  - img2fig
  - bootstrap-tables
  - git-revision-date-localized
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite

extra:
  disqus: 'fmlab'

extra_css:
  - assets/css/tables.css
  - assets/css/dark_theme.css
  - assets/css/codehilite.css
