site_name: "frealmyr's homelab"
site_url: 'https://fmlab.no/'

site_author: 'Fredrick Myrvoll'
site_description: 'Guides & tips for the homelab community'

repo_name: 'frealmyr/fmlab.no'
repo_url: 'https://github.com/frealmyr/fmlab.no'

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Home: index.md
  - Homelab:
      - introduction: homelab/introduction.md

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'purple'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'

extra:
  disqus: 'fmlab'