name: Publish mkdocs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy mkdocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@b1bb7cbaa91997e57d601309aac18facb028ff7d
        env:
          CUSTOM_DOMAIN: fmlab.no
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
